---
output:
  pdf_document: default
  html_document: default
---
```{r}
#Creating vectors
MyfirstVector <- c(3, 45, 56, 732)
MyfirstVector

is.numeric(MyfirstVector)
is.integer(MyfirstVector)
is.double(MyfirstVector)

V2 <- c(3L, 12L, 243L, 0L)
is.numeric(V2)
is.integer(V2)
is.double(V2)

V3 <- c("a", "B23", "Hello", 7)
V3
is.character(V3)
is.numeric(V3)

S1 <- seq(1,20)
S1

S2 <-seq(1,20,4)
S2

S3 <- 1:20
S3

R1 <- rep(0,10)
R1


```

```{r}
#Using [] for vectors
x <- c(1, 123, 534, 13, 4)
y <- seq(201, 350, 11)
z <- rep("Hi!", 3)

w <- c("a", "b", "c", "d", "e")
w

w[1]
w[2]
w[3]
w[-1]

v <- w[-3]

w[1:3]
w[3:5]
w[c(1, 3, 5)]
w[c(-2, -4)]
w[-3:-5]
w[1:3]


```

```{r}
#Vectorized operations
x <- rnorm(5)
x

#R-specific programming loop
for(i in x){
  print(i)
}

print(x[1])
print(x[2])
print(x[3])
print(x[4])
print(x[5])

#Conventional programming loop
for(j in 1:5){
  print(x[j])
}

N <- 100
a <- rnorm(N)
b <- rnorm(N)

#Vectorized approach
c <- a * b

#De-vectorized approach
d <- rep(NA, N)
for(i in 1:N){
  d[i] <- a[i] * b[i]
}

```
```{r}
#Packages in R
install.packages("ggplot2")
library(ggplot2)
qplot(data=diamonds, carat, price, colour=clarity, facets=.~clarity)
```

```{r}
#Homework : financial statement analysis
#Data
revenue <- c(14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50)
expenses <- c(12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96)

ProfitePerMonth <- revenue - expenses
ProfitePerMonth

ProfiteAfterTaxPerMonth <- ProfitePerMonth * 0.7
ProfiteAfterTaxPerMonth

ProfiteMarginPerMonth <- ProfiteAfterTaxPerMonth / revenue
ProfiteMarginPerMonth

MeanProfite <- mean(ProfiteAfterTaxPerMonth)
GoodMonths <- ProfiteAfterTaxPerMonth > MeanProfite
print("---------------------------------------------")
GoodMonths

BadMonths <- ProfiteAfterTaxPerMonth < MeanProfite
BadMonths

max(ProfiteAfterTaxPerMonth)

min(ProfiteAfterTaxPerMonth)
```


